language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "Qh9POfZ40nikOE4c+wlQWmJIcnuP9OR9zXpSOub28DcCnGmpEhn6sUCyXdaxaT/m+6rORSK9jnlVtAC1pSFQxD0MoZEM3+VVYT39/dj9YmCa9nxOIz2lMq94VqiOcQXCC6RT4zyE9I46RT4SZ/p2ZC95+Oip7RYjvrfMpdSgYm8FR3m70JeNiDtgTfFhxWZjxzUp6DanmnxZZzCOyWaKDdSyWBUEg0AEWfObCUezRCFCQXU1wratgQCgYWcFbTHYGuwIT51bxBGpW3q3l+IdFpg3/QDsugaYuW27pjEkVBhCcFpL2/QFtNxTxjjpfvZCF+WAfJS5SNIMjia5qXf9IkXHYyxrOnmTV9gv3hzh59eyOkolnMA4mKixl7YF5/hs24tmR5lQGLBD7xQ//3wVbIK2AD2c6C8fkVANLos7mWMtY011CR/O2o/RY9sMetr/osKgdAwkV5/Dolf3f8V2wvH1AHYbhA6Md8dtA2+8jY3HQ1TUtBVM5xWeu7PPyuHPoFKgU8UnHJmgxSYzofqTrWnR5YppFPKORVh6g69dUNRBZkt9m/9oYx6YJAR0c672TpPUikz28IFssDkzGImRcZsRf6gn4P1x5Rdtyy/H7xZfWbLloPXpgJ6LNzJYFhUrbrHqKL0M+ZbRCd4DIaT6hWap+C2/bJY+bbymNbQb+ts="
    # SNYK_API_TOKEN=[secure]
    - secure: "DoHoGKOcGJIZGGA256IF4xB6iDtVkPV8vPOMA7p9BckT67zuhCK584C0/UnJ6V09P81S2DA94pYYvkj6GWJs5nWVxPAvFRHe+oXbd0WN9WgSOB9ig1xd78Z5B1Wx4mdg9hcIdqWYu/ccT8VHl8odXOV2LW9VAWs0IMSEY6/ilWB3OGrUBXIIAOFIKrFz3ieU8lF2qeb0k9yl1u1BFwFVPLQOpceOOL6Sqqqw154qFnVF72y+Famu1ukBzElj13m2ie7oh0v2cFOm4aHEdBoxFYhcAEXJeYI1pv80PjnKHu7wzpavIJjQX+ikJDOVEaEkzkCaWkaHEs7g8j0Fy4fC6gL+MLS/J2QEH/Tlb64ocDI86Q+h/kbkXZMvY8B3XKSBP6kfXUFR3yN5VByukTmY7XOW1NH8HcOVMeY1wyEnztAbcmJPwZhvq6sEKhtE0H3lUiPv+8sDBuX1kdC9qPfLIAg3IoPefyopWLdX5EPNNK8eoyuEFUkEtMJVAuj5K6/7ao4e3Yw6BsQWzoT7Iu0+CJpoOqGIteDe1JeeNOpRtd6+laO6SMzEpYoq5LoGH+pR1W+2G24BhaFKp89TXxJ0wNrpkAk7lbwSow4U+nV+mRbq9tNGXQ9BzrxiYrlnMFHYotumD0HawRRxKvwi8LJqqu5liOmS3Cj0hNw1Vrkf24o="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "Qv/N5UGQQNnS+7nBEMa1eIKN0pz6bsyjjH1eWi+QmXIB4OqF713WfgiNBlxz0ZiM2A69g91E5qsYLD7UQ5f5NWqJaWdHU67p0gTOXYr+Hz0GL1aYkKNWDR3x/1DO0P7nD0Pkz+Qsv3pOx7MP8cW8Yu7XLcj039FeuPDfmbKgxpAo5C+E9IutPEmH7CmUliezazQpS9Akzeua0DRMmS5CB0XWPwjUL30cK1VYQsaxCwfaJ1z9WXszMihGyEMHKuETnoUabrCimK1qKuzXaIm6YUExmReQBB1796RBl+jpVJJ23CB/o1DB1Z8WEyaALWgwNBA/bu5vr0GvGDe4cDB09iUjPV5dVXctWAzEF2Cvu3NrFMgpVsMP+bQIeYZp96fuLIN67wj5LQGo+dvqNqZMERP/si806kBoT0W0oZw3MfWtkQPDQkDe5b0rf8XuGdSGUwe+RXcKI4Dxj9Xd5cuk4PSol9HqnzCWUlHJTguBCEwArWp9wFu66yiSw7MdWuKRXo9qBMrZoNY9OuVJ1uwbFH/sdc14AwsHZo8UR0aSH5lQXirTI6+tlmqjkSEKy+iLEQollX71DuhLOM1m8PKjWEkQWn0Wi4CYvae0xk3VFwzhbQYuRj4d0MnNG9RMpcYdjLr/GryXYL5tJayH4B4CkyQhNQDgbYfmDUWMG1cEnKs="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "Zhz+r7pt2fOhjLewLAH/pQnYngyPSHcbbnkJ2u1765SNxbdpNp4Jo+sI7mNZ1ElMnGEbx0KDK8U3+YCSJkNMSka3yFZcmZFOv4tS+uR5D3TLh5Sq6LC8J0d8N30RcZPhzhdrl8QDEimcGmsMNf9xiB+x7vqVWeWwbv3OKt1S0wtNJDvdbTPjUiT7bWMRyoXHy6+v50nw//MdIcMpM0le7+mA0JuIlhlL7hbgZ85FHERJ9oivSkJc6VuP9iTNpaq49ch0eU7jL165pT6mfmoQkqLBeVidb96ff4bWzZxs1dqztLhBZOna9SySN7Q1c8+pSK+GQPrkBu6zi/V3TtDkcsxq2S+DcddslYruA61WwZKUms0WosjyO/GlZP/DlRu6nTn+im6m/i76TY41HBfRrk2POXjWH4PLS1dUH/ngNAewyX/OT87TV9edFDiHoMUdJh7zPFUh3eQ1oiNi1oo3qXB2sZbjPrv90Yv+9S/R1qlOH5HQU2rtVwSpFo1sFeTeXTvqt02jVFuR6iSa2B7+uw5tmr67yptxINXyJsLKm0E0Ve89Nuzuv8nGiXynsc4si4YI1wC87PHMpgSgG+//XG5G/imE2sp1gJCF8P73xmjP+zzs30+YI9HKbKlVtu3W04CK/DVnOb4q4HfP5C7KiFJr3/L5P9t7L+eMAFjvoNY="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "Vi7xDG5NbMR8P96oWbM+Ny5aRS0iC1gqVbJUayzWhuytlA5sIndwGenDqPU7RFO8yxmhiK8W7wPCGv3nSlCmbAGFX4THc1bdDr8Vv80Qrx7WtTMqySpBNcfVHLu59Ho9Hd+zmUhtMezI9wVlCaFPOPu2cDynopckfiqGrY48zd+lnZ7dlrb5Tc3cfRSD7xEvVACozGAQaNzwaHiYxDMnDDhzY4fCa3UKmJB1xzWdtAemQonI5E3X4T3Nez7+nrH2ahM2AYkuFawvk0aKW37j1lW3sTfxtLrrvgYaQPdWNs2sjtEvIsUkziwFDWiwJ1ghPQeN/wON/xzigy+M5xWnVZYRAlafRK85QHlmEhYNQn+Apov4RAhtUJCJKTL+eTMMweDme+pyFPZ5496X9CFYHN26Bp6R9ncDpKFisFx8MfWJmKTw1r6xdb/EfJkJgEZhDE29DESGEmlupBMBTDhpkkpgMZ/Fsc+VhvXP9NcKpHcOaezWH1D+ORIckIEcDzH0nyCCIfRcflTLS6HUPaZMbWnffaTjxY1HLnUumqIha+cTk8mOwHuYX0kYh6J1f0a1rLW4Hd9P7i9+YIa2wTJB+kJzdkafF5hLMXCy4MJSbCOn43ULuJ8K/F8vt9F06MKK8+JY9kzUYrGInH8dOULyoG3qsAZ0PLfnaS1OjlFq/IQ="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
