language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "g9WGZt02YyaTx3KBX22AraxXgl4vtsWeuQChmylZtov/FSDEIPlPZ6b/dFsPNafYCL4s8WbXtv6LX6hyHEEe8ZIWyEx5oCB9tdDFyqSmCMkn5BbypMU69HFA8hfHWPZQoumkV0DBvMUS6BVwMUVQTS1aSMizaubQHfwAcpL82mrpD9UkapIhZESL7Z9fswG9TsB9HNaYe1t8MMErZkZNpSk1Di6GF8a+GnTxLibYigMKffo0wpVmKsF/k2gvaYkw+JKsrD6zjNtgQgfKOe1BTdqqg38ohmAm7hqUIhHiqq0xYcs9Uk3dIBf6mFurLYFTPTwujRRTMNiS/bnqmJeCe2DPqdE7GANbozpmSHz3cbc50ddl5WteP9kB/Qpc2Whgt6RlqyUTBLpm72wFqkPBbk7RqIQKT3Tm6nv/uFvJbi/BmgbmBEp1V1wmp/crRVD4wMBA0EzIJxhMd+dQfN6V1UMf56uZbTZP1MAqLbvnV6C7YuiAqtnl35z/e+T+RuBfrXYAuo8LErBAfF3kzZA8ELSJ1eX0JglyqZJbwu39RG7QsxFhahaXiVAf2lJg5TgUjGraLFAWVy1UDj/e45fNV32PpLVeyr+TrpUbxJ7ZWVlv4qkHRRPe6h4HgLBwxIXsDdDGSniGfpdoXryW3+fUVn4HCTakn6+Gd6cpv8oNmVw="
    # SNYK_API_TOKEN=[secure]
    - secure: "DoHoGKOcGJIZGGA256IF4xB6iDtVkPV8vPOMA7p9BckT67zuhCK584C0/UnJ6V09P81S2DA94pYYvkj6GWJs5nWVxPAvFRHe+oXbd0WN9WgSOB9ig1xd78Z5B1Wx4mdg9hcIdqWYu/ccT8VHl8odXOV2LW9VAWs0IMSEY6/ilWB3OGrUBXIIAOFIKrFz3ieU8lF2qeb0k9yl1u1BFwFVPLQOpceOOL6Sqqqw154qFnVF72y+Famu1ukBzElj13m2ie7oh0v2cFOm4aHEdBoxFYhcAEXJeYI1pv80PjnKHu7wzpavIJjQX+ikJDOVEaEkzkCaWkaHEs7g8j0Fy4fC6gL+MLS/J2QEH/Tlb64ocDI86Q+h/kbkXZMvY8B3XKSBP6kfXUFR3yN5VByukTmY7XOW1NH8HcOVMeY1wyEnztAbcmJPwZhvq6sEKhtE0H3lUiPv+8sDBuX1kdC9qPfLIAg3IoPefyopWLdX5EPNNK8eoyuEFUkEtMJVAuj5K6/7ao4e3Yw6BsQWzoT7Iu0+CJpoOqGIteDe1JeeNOpRtd6+laO6SMzEpYoq5LoGH+pR1W+2G24BhaFKp89TXxJ0wNrpkAk7lbwSow4U+nV+mRbq9tNGXQ9BzrxiYrlnMFHYotumD0HawRRxKvwi8LJqqu5liOmS3Cj0hNw1Vrkf24o="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "Qv/N5UGQQNnS+7nBEMa1eIKN0pz6bsyjjH1eWi+QmXIB4OqF713WfgiNBlxz0ZiM2A69g91E5qsYLD7UQ5f5NWqJaWdHU67p0gTOXYr+Hz0GL1aYkKNWDR3x/1DO0P7nD0Pkz+Qsv3pOx7MP8cW8Yu7XLcj039FeuPDfmbKgxpAo5C+E9IutPEmH7CmUliezazQpS9Akzeua0DRMmS5CB0XWPwjUL30cK1VYQsaxCwfaJ1z9WXszMihGyEMHKuETnoUabrCimK1qKuzXaIm6YUExmReQBB1796RBl+jpVJJ23CB/o1DB1Z8WEyaALWgwNBA/bu5vr0GvGDe4cDB09iUjPV5dVXctWAzEF2Cvu3NrFMgpVsMP+bQIeYZp96fuLIN67wj5LQGo+dvqNqZMERP/si806kBoT0W0oZw3MfWtkQPDQkDe5b0rf8XuGdSGUwe+RXcKI4Dxj9Xd5cuk4PSol9HqnzCWUlHJTguBCEwArWp9wFu66yiSw7MdWuKRXo9qBMrZoNY9OuVJ1uwbFH/sdc14AwsHZo8UR0aSH5lQXirTI6+tlmqjkSEKy+iLEQollX71DuhLOM1m8PKjWEkQWn0Wi4CYvae0xk3VFwzhbQYuRj4d0MnNG9RMpcYdjLr/GryXYL5tJayH4B4CkyQhNQDgbYfmDUWMG1cEnKs="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "G3Nu21OeW30Rsf/Kt6TgRTxdXKkrMC3ELSW0dDDm2jkM7KJj6AhqX5Vq0+ycmX0FN9YQgcwLwoulcsT/UfzILeJV33T4r7+7GrJRo2URXe4tPvifxjPChcXgoiyYkGmM1/FCeL/NBW8IGJDVV9UWtlYs37xHjA7zQYn/iKD6nvfOjyMTY1cJJSq68cNzecLInwuiEGmULf2xezdo1Hi0zdpzC8HU3mF36Jmkj5FnCNWrhFNo0TsH/5ZJA/ktQEZkUImv/L/mZmI64UsEbR4EnFdfetd/FypS1IBjRVouUSb4a2zAtc3KOe+V7Jwy4rFs3N+DuluOhJg0M4ZzKxM8nLjYE8e5bCQ9UXcmAs0B81SARYw6UCPH61V43CU+jxCKgSnk9JXoOyp1R1NNRFqQKZM2eugJ9SDulvuqZQMswGD1Uv++kAKHd+mx8shClGlw0p/hTfWBl2amjXTWEHUkMjVUx+NReWMAfJxyaFy4qBLc17d6spIHwOwC+k2kPBJNY64o4BQODyfjRauRtbUlwKbg/D9fjKbrIPRHW99q5r//ZYMXoI5mvF/viWyYwkl8ht6mQ7deBcPv4bbdE45DUZ/7LQnMsHhrp8bpVnamHZ0Iis0gMDmV0yHaPjvPpQi+2A+h4G1kH3m2nzKmaNV2+JqarVTD/uXb6DeO3HrEo/s="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "Vi7xDG5NbMR8P96oWbM+Ny5aRS0iC1gqVbJUayzWhuytlA5sIndwGenDqPU7RFO8yxmhiK8W7wPCGv3nSlCmbAGFX4THc1bdDr8Vv80Qrx7WtTMqySpBNcfVHLu59Ho9Hd+zmUhtMezI9wVlCaFPOPu2cDynopckfiqGrY48zd+lnZ7dlrb5Tc3cfRSD7xEvVACozGAQaNzwaHiYxDMnDDhzY4fCa3UKmJB1xzWdtAemQonI5E3X4T3Nez7+nrH2ahM2AYkuFawvk0aKW37j1lW3sTfxtLrrvgYaQPdWNs2sjtEvIsUkziwFDWiwJ1ghPQeN/wON/xzigy+M5xWnVZYRAlafRK85QHlmEhYNQn+Apov4RAhtUJCJKTL+eTMMweDme+pyFPZ5496X9CFYHN26Bp6R9ncDpKFisFx8MfWJmKTw1r6xdb/EfJkJgEZhDE29DESGEmlupBMBTDhpkkpgMZ/Fsc+VhvXP9NcKpHcOaezWH1D+ORIckIEcDzH0nyCCIfRcflTLS6HUPaZMbWnffaTjxY1HLnUumqIha+cTk8mOwHuYX0kYh6J1f0a1rLW4Hd9P7i9+YIa2wTJB+kJzdkafF5hLMXCy4MJSbCOn43ULuJ8K/F8vt9F06MKK8+JY9kzUYrGInH8dOULyoG3qsAZ0PLfnaS1OjlFq/IQ="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
